[build-system]
requires = ["setuptools>=64.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyDTO"
version = "0.1.0"
description = "A geospatial toolkit for calculating distances to California's geographic boundaries"
authors = [{name = "Rui Gao"}]
license = {text = "MIT"}
dependencies = [
    "geopandas>=0.14.0",
    "shapely>=2.0.0",
    "pyproj>=3.6.0",
    "fiona",
    "matplotlib>=3.8.0",
]
requires-python = ">=3.9"

[tool.setuptools]
packages = ["pyDTO"]
include-package-data = true

[tool.setuptools.package-data]
# include all kinds of data format
"pyDTO" = ["data/*"]
# "*" = ["data/*.shp", "data/*.shx", "data/*.dbf", "data/*.prj"]